# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: occupancy_flow_submission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='occupancy_flow_submission.proto',
  package='waymo.open_dataset.occupancy_flow',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1foccupancy_flow_submission.proto\x12!waymo.open_dataset.occupancy_flow\"o\n\x08Waypoint\x12#\n\x1bobserved_vehicles_occupancy\x18\x01 \x01(\x0c\x12#\n\x1boccluded_vehicles_occupancy\x18\x02 \x01(\x0c\x12\x19\n\x11\x61ll_vehicles_flow\x18\x03 \x01(\x0c\"i\n\x12ScenarioPrediction\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12>\n\twaypoints\x18\x02 \x03(\x0b\x32+.waymo.open_dataset.occupancy_flow.Waypoint\"\xec\x01\n\x13\x43hallengeSubmission\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x1a\n\x12unique_method_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x03 \x03(\t\x12\x13\n\x0b\x61\x66\x66iliation\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x13\n\x0bmethod_link\x18\x06 \x01(\t\x12S\n\x14scenario_predictions\x18\x07 \x03(\x0b\x32\x35.waymo.open_dataset.occupancy_flow.ScenarioPrediction'
)




_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='waymo.open_dataset.occupancy_flow.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='observed_vehicles_occupancy', full_name='waymo.open_dataset.occupancy_flow.Waypoint.observed_vehicles_occupancy', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occluded_vehicles_occupancy', full_name='waymo.open_dataset.occupancy_flow.Waypoint.occluded_vehicles_occupancy', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_vehicles_flow', full_name='waymo.open_dataset.occupancy_flow.Waypoint.all_vehicles_flow', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=181,
)


_SCENARIOPREDICTION = _descriptor.Descriptor(
  name='ScenarioPrediction',
  full_name='waymo.open_dataset.occupancy_flow.ScenarioPrediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scenario_id', full_name='waymo.open_dataset.occupancy_flow.ScenarioPrediction.scenario_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='waymo.open_dataset.occupancy_flow.ScenarioPrediction.waypoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=288,
)


_CHALLENGESUBMISSION = _descriptor.Descriptor(
  name='ChallengeSubmission',
  full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_name', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.account_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unique_method_name', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.unique_method_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authors', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.authors', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.affiliation', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method_link', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.method_link', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scenario_predictions', full_name='waymo.open_dataset.occupancy_flow.ChallengeSubmission.scenario_predictions', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=527,
)

_SCENARIOPREDICTION.fields_by_name['waypoints'].message_type = _WAYPOINT
_CHALLENGESUBMISSION.fields_by_name['scenario_predictions'].message_type = _SCENARIOPREDICTION
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['ScenarioPrediction'] = _SCENARIOPREDICTION
DESCRIPTOR.message_types_by_name['ChallengeSubmission'] = _CHALLENGESUBMISSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINT,
  '__module__' : 'occupancy_flow_submission_pb2'
  # @@protoc_insertion_point(class_scope:waymo.open_dataset.occupancy_flow.Waypoint)
  })
_sym_db.RegisterMessage(Waypoint)

ScenarioPrediction = _reflection.GeneratedProtocolMessageType('ScenarioPrediction', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIOPREDICTION,
  '__module__' : 'occupancy_flow_submission_pb2'
  # @@protoc_insertion_point(class_scope:waymo.open_dataset.occupancy_flow.ScenarioPrediction)
  })
_sym_db.RegisterMessage(ScenarioPrediction)

ChallengeSubmission = _reflection.GeneratedProtocolMessageType('ChallengeSubmission', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGESUBMISSION,
  '__module__' : 'occupancy_flow_submission_pb2'
  # @@protoc_insertion_point(class_scope:waymo.open_dataset.occupancy_flow.ChallengeSubmission)
  })
_sym_db.RegisterMessage(ChallengeSubmission)


# @@protoc_insertion_point(module_scope)
